spring:
  neo4j:
    uri: ${NEO4J_URL}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
server:
  port: ${SERVER_PORT}
logging:
  level:
    org:
      springframework:
        data:
          neo4j: ${NEO4J_LOG_LEVEL}